### ISSUE TITLE
Installed different code from master branch

### ISSUE THREAD

**Issue by sindu12jun** [unimodules/react-native-unimodules#110]
I am trying to use expo-local-authentification using react-native-unimodules, but after module installed, I go into `node_modules/expo-local-authentification`, I found the code is different from the master branch, which has the same npm version number.

This is the code installed by react-native-unimodules
![image](https://user-images.githubusercontent.com/21314589/74404149-c159fc80-4e7d-11ea-9cf8-ca88feac82d3.png)

This is the same file in the master branch:
![image](https://user-images.githubusercontent.com/21314589/74404211-e8b0c980-4e7d-11ea-9378-365160666a04.png)

Apparently, the code in master branch is right

**Comment by sjchmiela** [comment]
Hey @sindu12jun! Let me clarify how do we run things around Git and releases here at Expo. `react-native-unimodules` is a "wrapper package" that depended on a couple of unimodules, a foundation of sorts, it doesn't provide almost any functionality. `expo-local-authentication` which you ask about is published from [`expo/expo`](https://github.com/expo/expo) repository, so different than this one. (We recently moved `react-native-unimodules` there to centralize all the work—this should be easier to apprehend.)

`master` branch is our "most recent state of code" which may not be released yet in NPM. We try to log any notable changes in the package's changelog, an example of such changelog for `expo-local-authentication` can be found [here](https://github.com/expo/expo/blob/master/packages/expo-local-authentication/CHANGELOG.md).

So in general, it's rather expected that sometimes code from `master` is different than the last published—we do not (maybe "yet") publish new versions every time a change is made to the package.

I hope that the issue you were facing has been fixed by a more recent version of `expo-local-authentication`! 🙂
