### ISSUE TITLE
NOOOO!!! npm install react-native-unimodules has removed my custom native module

### ISSUE THREAD

**Issue by herbertvuijk** [unimodules/react-native-unimodules#113]
Days of work GONE by running NPM install react-native-unimodules. I was working on a native module in node_modules/mymodule. After running npm install react-native-unimodules the code is removed from the module :(. Why is this not stated in the documentation? This is shitty :(

**Comment by sjchmiela** [comment]
Hey @herbertvuijk! I'm really sorry for your loss. Unfortunately I don't know of any way to restore files deleted by `npm install` apart from the regular files restoration processes (which I don't think would render any interesting results in this case). 😕 

When it comes to the reason your native module got deleted — I don't think `node_modules` is a good place that may be considered anyhow persistent storage. Not only is it recommended to git-ignore it, but also, as you have experienced, package managers may decide to delete it (or parts of it) when (re)installing dependencies.

_In fact it's just a coincidence that your native module got deleted when you decided to install `react-native-unimodules`. You could have been upgrading `react` version and your module could have been deleted as well._

If you want to develop a custom native module, I would recommend putting it into a separate directory outside of any `node_modules` and linking it into your example project using Yarn's [`link:../path/`](https://classic.yarnpkg.com/en/docs/cli/add). This way if you changed something inside `node_modules/mymodule`, you would actually modify the source of the library via a filesystem link.

Since it looks like it wasn't `react-native-unimodules` which caused your code loss, I will let myself close this issue. I hope you find motivation to rewrite your custom native module in a more persistent place! 🙂

**Comment by herbertvuijk** [comment]
A bit late, but thanks for you elaborated answer.. In the meanwhile I found the motivation to start over and do it better this time. By now I realize I was not really understanding what I was doing when it comes to location of development and using NPM.. Anyway, get it now and everything is running fine. Thanks for taking the time to respond to clearly a noob mistake.
