### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by Psiiirus** [unimodules/react-native-unimodules#121]
Hi guys,
i am using this lib directly because I had to eject my project but unf. with each update of react-native-unimodules I feel a bit lost because there is no documentation what has changed and what do i get if i update.

Is the 0.8.0 version stable?

Cheers,
Toni

**Comment by Psiiirus** [comment]
@bbarthec would be so kind to explain where we can find the change logs if react-native-unimodules gets a new version?

**Comment by bbarthec** [comment]
Uh! @Psiiirus, you're right! 😞 Since we partially automated release and versioning process of this package as a part of main https://github.com/expo/expo repository we're missing new entries in `CHANGELOG` file 😞 Sorry for that!
Regarding stability of versions: we consider that every version is `stable` unless it's marked with `rc`, `alpha` or other tags suggesting otherwise.

**Comment by Psiiirus** [comment]
@bbarthec
thanks for the information about the stability. Besides this I think it will be great for all developer to know why and when they should updated the unimodules. :-) Is there any source where I can find this kind of information? even if they are splitted across repos?

**Comment by bbarthec** [comment]
@Psiiirus, I've added missing entries to CHANGELOG file. Unfortunately those might tell you almost nothing. Bumping this package version is mostly associated with updating it's dependencies, so to get the bigger picture of what might have changed between versions I recommend reading the dependencies' CHANGELOGs or/and see the commits history of updated dependencies.

**Comment by Psiiirus** [comment]
okay thanks @bbarthec
