### ISSUE TITLE
Why is Minimum SDK 21 ? 

### ISSUE THREAD

**Issue by ndjemel** [unimodules/react-native-unimodules#26]
What exactly do Unimodules implement that requite API Level 21 on Android ?

**Comment by ouabing** [comment]
This is also my concern. Is it because some APIs are not available under API Level 21? If so can we avoid using these APIs to support older models?

**Comment by solidfox** [comment]
Agreed, KitKat @ SDK 19 and JellyBean @ 16 still has about 10% of the users.

**Comment by Ashoat** [comment]
Adding a little color to this issue: I was excited to give unimodules a try, but had to drop it once I realized the min SDK has to be 21. I'm sure folks are aware, but much of the developing world is still stuck on older versions of Android. Based on Android's [Distribution dashboard](https://developer.android.com/about/dashboards), about 10.6% of users are using API levels 16-21. 

This certainly makes developing for the Android ecosystem harder than iOS, where old versions are much less common.

I think the reason that the min SDK is 21 is because Expo's is. Before the effort to split everything into modules, the whole codebase was constructed on the assumption that the min SDK is 21.

It might not be super difficult to get the unimodules core and React Native adapter compatible with older SDK versions, but that wouldn't be useful without at least some of the existing unimodules getting a similar rewrite. Such an effort would probably be hard for Expo employees to prioritize.

**Comment by tsapeta** [comment]
Hey guys,
Thanks @Ashoat for your explanation, it's correct that the reason for `minSdkVersion` be set to 21 was the Expo Client. However most of the unimodules don't require SDK 21 and should still work with SDK 16, so we're going to give you an option to change this version by yourself in your project's `build.gradle`.
Here is the open pull requests with these changes https://github.com/expo/expo/pull/4071, so stay tuned 😉

**Comment by ouabing** [comment]
Hey @tsapeta , as your PR is merged, is it safe to use unimodule in Android below SDK 21 now?

**Comment by tsapeta** [comment]
Hey @ouabing,
It was never my intention to make them safe to use below Android SDK21, this PR only allows you to change `minimumSdkVersion` that is set in unimodules' build.gradle, however it doesn't guarantee they will work as expected. Expo modules still doesn't support Android SDKs below 21, but it doesn't mean you cannot force them to use lower one. Now they're using appropriate versions defined in root project's buildscript extension, see here: https://github.com/expo/expo/blob/49b713237189aadc8ebfadb2e93775dc6182a92b/templates/expo-template-bare-minimum/android/build.gradle#L4-L10
This is also commonly used in other libraries such as [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and new project templates.

However if you change minimum SDK version there, especially to a lower version, Gradle may not build your project if any of the unimodule uses API that wasn't available in the SDK you use. I believe most of them can work in SDK19 too (that means just a few of them use APIs not available in SDK19).

**Comment by ouabing** [comment]
@tsapeta Gotcha, thanks!

**Comment by Ashoat** [comment]
I managed to get `react-native-unimodules` and `expo-media-library` working on an Android 4.4 device thanks to this work! Thanks a bunch @tsapeta.

Would be great if the community could build a table of Unimodules that have been tested against earlier Android API levels so we could know what works and what doesn't.

**Comment by briantical** [comment]
> I managed to get `react-native-unimodules` and `expo-media-library` working on an Android 4.4 device thanks to this work! Thanks a bunch @tsapeta.
> 
> Would be great if the community could build a table of Unimodules that have been tested against earlier Android API levels so we could know what works and what doesn't.

Is it possible for you to share your implementation. I am still failing to get it working.

**Comment by Ashoat** [comment]
The repo is https://github.com/CommE2E/comm
