### ISSUE TITLE
ModuleRegistryConsumer not found 

### ISSUE THREAD

**Issue by zhuliminl** [unimodules/react-native-unimodules#72]
![image](https://github.com/zhuliminl/imgs/blob/master/bug_1.png?raw=true)

**Comment by zhuliminl** [comment]
every expo-xx module has the same error with ModuleRegistryConsumer not found

**Comment by sjchmiela** [comment]
Upgrade the affected modules to more recent versions. 🙂

**Comment by sjchmiela** [comment]
It could also be that some third-party library is depending on `expo-image-picker` (that's why your project ends up including it) but the version requirement is old (such library is eg. `react-native-gifted-chat` which depends on `expo-image-picker@5` which is incompatible with latest `r-n-u` releases). 🙂

**Comment by DeepakNatraj** [comment]
Hi @zhuliminl 

Same issue for me.

While updating from 32 to expoSDK 33  found a issue that
' cannot find symbol class ModuleRegistryConsumer  ' in all expo modules
Example : expo - ads - facebook. ( import org.unimodules.core.interface.ModuleRegistryConsumer )
Kindly help me to solve this issue

I am in production stage. can anyone help me to solve this...
