### ISSUE TITLE
Android Pedometer still unavailable in Expo-Unimodules

### ISSUE THREAD

**Issue by antoinedelp** [unimodules/react-native-unimodules#98]
Hi, 

I am using react-native-unimodules to use expo-sensors in my bare React Native app in order to access Expo's Pedometer.
[There was an issue in Expo V35 making the Android Pedometer unavailable:](https://github.com/expo/expo/issues/4895) apparently, it was fixed in Expo V36, but I still have the same error message when trying to access Pedometer.getStepCountAsync ("Getting step count date range is not supported on Android yet.")

How can I use the newest version of Expo's Pedometer through react-native-unimodules and expo-sensors? I am not sure about how the relation between Expo, expo-sensors and react-native-unimodules work. 

- React-native 0.61.5
- expo-sensors: 8.0.0
- react-native-unimodules: 0.7.0

**Comment by antoinedelp** [comment]
Hi @tsapeta ! Thanks for the hard work and best wishes for 2020 ;)  any chances you know when this will be available?

**Comment by sjchmiela** [comment]
Hey @antoinedelp! This hasn't been fixed in SDK36 — pedometer in `expo-sensors` relies on some Android functionality that isn't common among Android devices. Pedometer in managed workflow (in Expo) uses Google Play Services to fetch steps associated with a Google profile.

I'll close this issue in favor of tracking this feature request in one place in https://github.com/expo/expo/issues/4895.
